2025-08-12 19:11:12,464- CRITICAL: Could not connect to MongoDB : Bad database name "contacts/" [in /Users/omprakashmahato/Documents/flask/ommahato_webapp/app.py:43]
2025-08-12 19:12:34,756- CRITICAL: Could not connect to MongoDB : SSL handshake failed: ac-eqdhrte-shard-00-01.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-eqdhrte-shard-00-00.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-eqdhrte-shard-00-02.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 689bd8544d2039d62305b81e, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-eqdhrte-shard-00-00.32fb7vz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-eqdhrte-shard-00-00.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-eqdhrte-shard-00-01.32fb7vz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-eqdhrte-shard-00-01.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-eqdhrte-shard-00-02.32fb7vz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-eqdhrte-shard-00-02.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]> [in /Users/omprakashmahato/Documents/flask/ommahato_webapp/app.py:43]
2025-08-12 19:13:48,606- CRITICAL: Could not connect to MongoDB : SSL handshake failed: ac-eqdhrte-shard-00-01.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-eqdhrte-shard-00-00.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-eqdhrte-shard-00-02.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 689bd89edb13f43628ad49a3, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-eqdhrte-shard-00-00.32fb7vz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-eqdhrte-shard-00-00.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-eqdhrte-shard-00-01.32fb7vz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-eqdhrte-shard-00-01.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-eqdhrte-shard-00-02.32fb7vz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-eqdhrte-shard-00-02.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]> [in /Users/omprakashmahato/Documents/flask/ommahato_webapp/app.py:43]
2025-08-12 19:24:44,629- CRITICAL: Could not connect to MongoDB : SSL handshake failed: ac-eqdhrte-shard-00-02.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-eqdhrte-shard-00-01.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-eqdhrte-shard-00-00.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 689bdb2e0adcf5d32f88c827, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-eqdhrte-shard-00-00.32fb7vz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-eqdhrte-shard-00-00.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-eqdhrte-shard-00-01.32fb7vz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-eqdhrte-shard-00-01.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-eqdhrte-shard-00-02.32fb7vz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-eqdhrte-shard-00-02.32fb7vz.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]> [in /Users/omprakashmahato/Documents/flask/ommahato_webapp/app.py:43]
2025-08-12 19:29:30,943- CRITICAL: Could not connect to MongoDB : bad auth : authentication failed, full error: {'ok': 0, 'errmsg': 'bad auth : authentication failed', 'code': 8000, 'codeName': 'AtlasError'} [in /Users/omprakashmahato/Documents/flask/ommahato_webapp/app.py:43]
2025-08-12 19:35:43,406- CRITICAL: Could not connect to MongoDB : bad auth : authentication failed, full error: {'ok': 0, 'errmsg': 'bad auth : authentication failed', 'code': 8000, 'codeName': 'AtlasError'} [in /Users/omprakashmahato/Documents/flask/ommahato_webapp/app.py:43]
2025-08-12 19:36:38,671- CRITICAL: Could not connect to MongoDB : bad auth : authentication failed, full error: {'ok': 0, 'errmsg': 'bad auth : authentication failed', 'code': 8000, 'codeName': 'AtlasError'} [in /Users/omprakashmahato/Documents/flask/ommahato_webapp/app.py:43]
2025-08-12 19:38:02,454- CRITICAL: Could not connect to MongoDB : bad auth : authentication failed, full error: {'ok': 0, 'errmsg': 'bad auth : authentication failed', 'code': 8000, 'codeName': 'AtlasError'} [in /Users/omprakashmahato/Documents/flask/ommahato_webapp/app.py:43]
2025-08-12 19:39:44,284- CRITICAL: Could not connect to MongoDB : bad auth : authentication failed, full error: {'ok': 0, 'errmsg': 'bad auth : authentication failed', 'code': 8000, 'codeName': 'AtlasError'} [in /Users/omprakashmahato/Documents/flask/ommahato_webapp/app.py:43]
